"""Agregando dirección a perfil

Revision ID: 88087a07e202
Revises: 26802eda27f5
Create Date: 2026-02-17 15:56:27.694097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88087a07e202'
down_revision: Union[str, Sequence[str], None] = '26802eda27f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('direccion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil', 'direccion')
    # ### end Alembic commands ###
